CREATE TYPE "public"."location_status" AS ENUM('draft', 'building', 'launched', 'paused', 'archived');--> statement-breakpoint
CREATE TABLE "locations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"status" "location_status" DEFAULT 'draft' NOT NULL,
	"brand_display_name" text,
	"brand_location_label" text,
	"brand_legal_name" text,
	"contact_address" text,
	"contact_phone" text,
	"contact_phone_e164" text,
	"contact_support_email" text,
	"domain_apex" text,
	"domain_canonical" text,
	"domain_locales" jsonb DEFAULT '["en"]'::jsonb,
	"domain_default_locale" text DEFAULT 'en',
	"visual_primary_color" text,
	"visual_accent_color" text,
	"visual_display_font" text DEFAULT 'Anton',
	"visual_body_font" text DEFAULT 'Inter',
	"visual_logo_url" text,
	"fareharbor_shortname" text,
	"fareharbor_default_flow_id" text,
	"fareharbor_tour_catalog" jsonb DEFAULT '[]'::jsonb,
	"marketing_from_name" text,
	"marketing_sending_subdomain" text,
	"marketing_reply_to_email" text,
	"marketing_ai_chat_kb" text,
	"socials_instagram" text,
	"socials_tiktok" text,
	"socials_facebook" text,
	"vercel_project_id" text,
	"vercel_edge_config_id" text,
	"github_repo_url" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "locations_slug_unique" UNIQUE("slug")
);
