// Catalog of secret kinds the Integrations tab exposes. Adding a new
// integration is a one-line entry here — schema stays generic. Lives in its
// own non-"use server" module because "use server" files can only export
// async functions.

export const SECRET_KINDS = {
  META_CAPI_TOKEN: {
    label: "Meta CAPI access token",
    description:
      "System User access token from Meta Business Manager. Used by the location site for non-Purchase server-side events (Lead, InitiateCheckout, ViewContent). FareHarbor's own CAPI handles Purchase.",
    placeholder: "EAAB…",
  },
  FAREHARBOR_WEBHOOK_SECRET: {
    label: "FareHarbor webhook signing secret",
    description:
      "HMAC secret for validating incoming FareHarbor booking webhooks. Generated by you; pasted into the FareHarbor dashboard webhook config and stored here so the location site can verify signatures.",
    placeholder: "fh_…",
  },
  GOOGLE_ADS_CONVERSION_API_TOKEN: {
    label: "Google Ads Conversion API token",
    description:
      "OAuth access token for server-side conversion uploads. Only needed if this location runs the Google Ads enhanced-conversions integration on our side.",
    placeholder: "ya29…",
  },
} as const;

export type SecretKind = keyof typeof SECRET_KINDS;

// Where each secret's management UI lives. Server-side tracking tokens surface
// under the Tracking page (alongside the CAPI toggle); the rest under Integrations.
export const TRACKING_SECRET_KINDS: SecretKind[] = [
  "META_CAPI_TOKEN",
  "GOOGLE_ADS_CONVERSION_API_TOKEN",
];
export const INTEGRATION_SECRET_KINDS: SecretKind[] = [
  "FAREHARBOR_WEBHOOK_SECRET",
];
